[package]
name = "calcium-voxel"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = "0.15"
calcium-rendering-world3d = {path = "../calcium-rendering-world3d"}
