[package]
name = "calcium-rendering-static"
version = "0.0.1"
authors = ["Layl <LaylConway@users.noreply.github.com>"]
description = "The future home of the calcium rendering library"
license = "MIT/Apache-2.0"

[dependencies]
slog = "2"
calcium-rendering = {path = "../calcium-rendering"}
calcium-rendering-vulkano = {path = "../calcium-rendering-vulkano"}
calcium-rendering-world3d = {path = "../calcium-rendering-world3d"}
calcium-rendering-world3d-vulkano = {path = "../calcium-rendering-world3d-vulkano"}
