[package]
name = "flowy"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = "0.14"
palette = "0.2"
pistoncore-input = "0.18"
rusttype = "0.2"
glyphlayout = {path = "../glyphlayout"}
screenmath = {path = "../screenmath"}
