[package]
name = "calcium"
version = "0.0.1"
authors = ["Layl <LaylConway@users.noreply.github.com>"]
description = "The future home of the calcium rendering library"
license = "MIT/Apache-2.0"

[dependencies]
