[package]
name = "calcium-rendering-vulkano"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = "0.15"
image = "0.15"
slog = "2"
vulkano = "0.6"
calcium-rendering = {path = "../calcium-rendering"}
