[package]
name = "calcium-rendering-3d"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = "0.15"
slog = "2.0.5"
wavefront_obj = "5.0.0"
calcium-rendering = {path = "../calcium-rendering"}
