[package]
name = "calcium-rendering-gfx"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = "0.14"
image = "0.14"
pistoncore-input = "0.18"
slog = "2"
calcium-rendering = {path = "../calcium-rendering"}
