[package]
name = "calcium-rendering-gfx"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = "0.15"
gfx = "0.16"
image = "0.15"
slog = "2"
calcium-rendering = {path = "../calcium-rendering"}
