[package]
name = "carpenter"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = "0.14"
calcium-rendering = {path = "../../libraries/rendering/calcium-rendering"}
calcium-rendering-static = {path = "../../libraries/rendering/calcium-rendering-static"}
calcium-rendering-vulkano = {path = "../../libraries/rendering/calcium-rendering-vulkano"}
slog = "2"
slog-async = "2"
slog-term = "2"
vulkano = "0.5"
vulkano-win = "0.5"
winit = "0.7"

# If you want optimizations in dev while keeping debug symbols, enable this
#[profile.dev]
#opt-level = 3
