[package]
name = "calcium-window-winit"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = "0.14"
vulkano = "0.5"
vulkano-win = "0.5"
winit = "0.7"
calcium-window = {path = "../calcium-window"}
