[package]
name = "calcium-rendering-vulkano-shaders"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
vulkano = "0.5"

[build-dependencies]
vulkano-shaders = "0.5"
